export default [
  {
    name: "Dvidh",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: true,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 13,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02BAC724",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Darkomeh",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Rogue",
    zone: "Eastern Plaguelands",
    note: "Darko",
    officerNote: "",
    isOnline: true,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 9,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02763168",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Mugur",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Warlock",
    zone: "Silithus",
    note: "Nesimtitul",
    officerNote: "",
    isOnline: true,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 162,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01DF83BF",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Pinteaviteaz",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Blackrock Mountain",
    note: "",
    officerNote: "1 (Prezenta Raid)",
    isOnline: true,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 7,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726C21",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Ezekielrage",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "",
    officerNote: "8 (prezente raid)",
    isOnline: true,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 11,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-029F625F",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Utherlol",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "8.5 (prezente raid)",
    isOnline: true,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 10,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027FC4FA",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Danddy",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "25 (Prezenta Raid)",
    isOnline: true,
    status: 1,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 8,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747FDF",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Duracell",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Druid",
    zone: "Eastern Plaguelands",
    note: "Duracell / Feral / Alche / Lw",
    officerNote: "29.5 (Prezenta Raid)",
    isOnline: true,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 3,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725B27",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Reddog",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Rogue",
    zone: "Stranglethorn Vale",
    note: "",
    officerNote: "17 (Prezenta Raid)",
    isOnline: true,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 12,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A12CE1",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Zanadar",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Warrior",
    zone: "Duskwood",
    note: "Engi/Mining",
    officerNote: "33 (prezente raid)",
    isOnline: true,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 81,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0270F561",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Garthpriest",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Priest",
    zone: "Ironforge",
    note: "alch/herb",
    officerNote: "31 (Prezenta Raid)",
    isOnline: true,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 5,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725C37",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Moonkeep",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Druid",
    zone: "Stranglethorn Vale",
    note: "alch/herb",
    officerNote: "30 (Prezenta Raid)",
    isOnline: true,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 4,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725BC8",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Seeltze",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Warlock",
    zone: "Ironforge",
    note: "tailor/eng",
    officerNote: "33 (Prezenta Raid)",
    isOnline: true,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 6,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726A2C",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Squidmarket",
    rankName: "Trial",
    rankIndex: 6,
    level: 1,
    class: "Mage",
    zone: "Ironforge",
    note: "Valiza",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 46,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724D43",
    lastOnline: 1734152400,
    realmName: "LivingFlame",
  },
  {
    name: "Parintele",
    rankName: "Trial",
    rankIndex: 6,
    level: 2,
    class: "Priest",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 151,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B0C38F",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Zeeryon",
    rankName: "Trial",
    rankIndex: 6,
    level: 8,
    class: "Rogue",
    zone: "Elwynn Forest",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 139,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A74B02",
    lastOnline: 1734476400,
    realmName: "LivingFlame",
  },
  {
    name: "Andrbank",
    rankName: "Trial",
    rankIndex: 6,
    level: 10,
    class: "Rogue",
    zone: "Ironforge",
    note: "Valiza",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 45,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724CF5",
    lastOnline: 1733947200,
    realmName: "LivingFlame",
  },
  {
    name: "Andreibank",
    rankName: "Trial",
    rankIndex: 6,
    level: 10,
    class: "Druid",
    zone: "Ironforge",
    note: "Valiza",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 44,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724CE2",
    lastOnline: 1734152400,
    realmName: "LivingFlame",
  },
  {
    name: "Garthtrans",
    rankName: "Trial",
    rankIndex: 6,
    level: 10,
    class: "Mage",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 55,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725C23",
    lastOnline: 1739062800,
    realmName: "LivingFlame",
  },
  {
    name: "Shadowkeeper",
    rankName: "Trial",
    rankIndex: 6,
    level: 10,
    class: "Warlock",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 106,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0275B01E",
    lastOnline: 1738760400,
    realmName: "LivingFlame",
  },
  {
    name: "Decaeneus",
    rankName: "Trial",
    rankIndex: 6,
    level: 12,
    class: "Priest",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 146,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02AAEFB6",
    lastOnline: 1738605600,
    realmName: "LivingFlame",
  },
  {
    name: "Madlif",
    rankName: "Trial",
    rankIndex: 6,
    level: 14,
    class: "Warrior",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 126,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-028770D1",
    lastOnline: 1739008800,
    realmName: "LivingFlame",
  },
  {
    name: "Ysus",
    rankName: "Trial",
    rankIndex: 6,
    level: 14,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 118,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027E27BE",
    lastOnline: 1728946800,
    realmName: "LivingFlame",
  },
  {
    name: "Vøj",
    rankName: "Trial",
    rankIndex: 6,
    level: 15,
    class: "Hunter",
    zone: "Darkshore",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 117,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027DF228",
    lastOnline: 1728756000,
    realmName: "LivingFlame",
  },
  {
    name: "Nevadar",
    rankName: "Trial",
    rankIndex: 6,
    level: 17,
    class: "Warlock",
    zone: "Westfall",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 143,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A8C478",
    lastOnline: 1734627600,
    realmName: "LivingFlame",
  },
  {
    name: "Zeryon",
    rankName: "Trial",
    rankIndex: 6,
    level: 19,
    class: "Mage",
    zone: "Elwynn Forest",
    note: "Mining/Engi",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 141,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A862D5",
    lastOnline: 1734631200,
    realmName: "LivingFlame",
  },
  {
    name: "Peacefulness",
    rankName: "Trial",
    rankIndex: 6,
    level: 20,
    class: "Druid",
    zone: "Wetlands",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: 0,
    achievementRank: 2,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A12CE9",
    lastOnline: 1739102400,
    realmName: "LivingFlame",
  },
  {
    name: "Croco",
    rankName: "Trial",
    rankIndex: 6,
    level: 26,
    class: "Warrior",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 159,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02BB1478",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Svas",
    rankName: "Trial",
    rankIndex: 6,
    level: 26,
    class: "Warlock",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 149,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02AFF7EF",
    lastOnline: 1736719200,
    realmName: "LivingFlame",
  },
  {
    name: "Meowtzy",
    rankName: "Trial",
    rankIndex: 6,
    level: 28,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 128,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-029729FA",
    lastOnline: 1737367200,
    realmName: "LivingFlame",
  },
  {
    name: "Ophilios",
    rankName: "Trial",
    rankIndex: 6,
    level: 29,
    class: "Priest",
    zone: "Hillsbrad Foothills",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 148,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02AFF78B",
    lastOnline: 1736373600,
    realmName: "LivingFlame",
  },
  {
    name: "Compfused",
    rankName: "Trial",
    rankIndex: 6,
    level: 30,
    class: "Mage",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 26,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02185A41",
    lastOnline: 1739044800,
    realmName: "LivingFlame",
  },
  {
    name: "Marshäl",
    rankName: "Trial",
    rankIndex: 6,
    level: 31,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 116,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027DEC40",
    lastOnline: 1731286800,
    realmName: "LivingFlame",
  },
  {
    name: "Garthshot",
    rankName: "Trial",
    rankIndex: 6,
    level: 35,
    class: "Hunter",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 152,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B2B71D",
    lastOnline: 1738825200,
    realmName: "LivingFlame",
  },
  {
    name: "Cagemagul",
    rankName: "Trial",
    rankIndex: 6,
    level: 38,
    class: "Mage",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 137,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A457A5",
    lastOnline: 1733698800,
    realmName: "LivingFlame",
  },
  {
    name: "Fordread",
    rankName: "Trial",
    rankIndex: 6,
    level: 40,
    class: "Mage",
    zone: "Ironforge",
    note: "Alt Palasor",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 60,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726927",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Sobolanu",
    rankName: "Trial",
    rankIndex: 6,
    level: 41,
    class: "Warlock",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 40,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724B1D",
    lastOnline: 1737223200,
    realmName: "LivingFlame",
  },
  {
    name: "Biserica",
    rankName: "Trial",
    rankIndex: 6,
    level: 43,
    class: "Priest",
    zone: "Loch Modan",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 160,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02BC042A",
    lastOnline: 1738756800,
    realmName: "LivingFlame",
  },
  {
    name: "Destrabalanu",
    rankName: "Trial",
    rankIndex: 6,
    level: 45,
    class: "Druid",
    zone: "Ironforge",
    note: "Oslobanu alt",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 49,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725B8F",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Isteval",
    rankName: "Trial",
    rankIndex: 6,
    level: 48,
    class: "Paladin",
    zone: "Feralas",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 130,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A0B99F",
    lastOnline: 1738832400,
    realmName: "LivingFlame",
  },
  {
    name: "Airana",
    rankName: "Trial",
    rankIndex: 6,
    level: 50,
    class: "Priest",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 125,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02865EFB",
    lastOnline: 1731441600,
    realmName: "LivingFlame",
  },
  {
    name: "Karolusrex",
    rankName: "Trial",
    rankIndex: 6,
    level: 52,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 155,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B30EA3",
    lastOnline: 1738112400,
    realmName: "LivingFlame",
  },
  {
    name: "Bossaru",
    rankName: "Trial",
    rankIndex: 6,
    level: 53,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 18,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01D5E546",
    lastOnline: 1735340400,
    realmName: "LivingFlame",
  },
  {
    name: "Jokiy",
    rankName: "Trial",
    rankIndex: 6,
    level: 53,
    class: "Druid",
    zone: "Tanaris",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 122,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0280F5C0",
    lastOnline: 1731805200,
    realmName: "LivingFlame",
  },
  {
    name: "Lockfury",
    rankName: "Trial",
    rankIndex: 6,
    level: 53,
    class: "Warlock",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 110,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027839C1",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Imonyrside",
    rankName: "Trial",
    rankIndex: 6,
    level: 58,
    class: "Mage",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 133,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A200E8",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Axieros",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "herb/alch",
    officerNote: "3 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 96,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02749773",
    lastOnline: 1732140000,
    realmName: "LivingFlame",
  },
  {
    name: "Burexin",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Priest",
    zone: "Burning Steppes",
    note: "",
    officerNote: "1 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 114,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027D5D96",
    lastOnline: 1738947600,
    realmName: "LivingFlame",
  },
  {
    name: "Dicineus",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Priest",
    zone: "Ironforge",
    note: "",
    officerNote: "0.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 147,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02AB8E8B",
    lastOnline: 1737406800,
    realmName: "LivingFlame",
  },
  {
    name: "Elunne",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Druid",
    zone: "Stonetalon Mountains",
    note: "",
    officerNote: "1 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 23,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01F4C100",
    lastOnline: 1738807200,
    realmName: "LivingFlame",
  },
  {
    name: "Fockr",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "seal team six",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 31,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0249FB6D",
    lastOnline: 1739109600,
    realmName: "LivingFlame",
  },
  {
    name: "Gigicutitaru",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Rogue",
    zone: "Silithus",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 32,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02612510",
    lastOnline: 1739037600,
    realmName: "LivingFlame",
  },
  {
    name: "Greuceanull",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 145,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02AA5AB4",
    lastOnline: 1739120400,
    realmName: "LivingFlame",
  },
  {
    name: "Irshia",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 14,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01CDCD61",
    lastOnline: 1732741200,
    realmName: "LivingFlame",
  },
  {
    name: "Keenblade",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Warrior",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 86,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747EB9",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Keltharius",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Paladin",
    zone: "Duskwood",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 120,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027E9F7B",
    lastOnline: 1738494000,
    realmName: "LivingFlame",
  },
  {
    name: "Kàzuhira",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 78,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0272CFE6",
    lastOnline: 1738843200,
    realmName: "LivingFlame",
  },
  {
    name: "Røbøt",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Rogue",
    zone: "Arathi Basin",
    note: "Smelting/GoblinEngineer/Cooking",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 119,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027E4C17",
    lastOnline: 1730228400,
    realmName: "LivingFlame",
  },
  {
    name: "Selynne",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Hunter",
    zone: "Blackrock Mountain",
    note: "Friend of Fock",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: 0,
    achievementRank: 1,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02493BBD",
    lastOnline: 1739088000,
    realmName: "LivingFlame",
  },
  {
    name: "Sfinx",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Mage",
    zone: "Stormwind City",
    note: "Alt Nesimtitul",
    officerNote: "Nesimtitul",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 15,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01D09BF4",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Starflowx",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "1 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 109,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0276380D",
    lastOnline: 1738544400,
    realmName: "LivingFlame",
  },
  {
    name: "Teglosu",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 37,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0270F25B",
    lastOnline: 1731751200,
    realmName: "LivingFlame",
  },
  {
    name: "Unthena",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Druid",
    zone: "Blackrock Mountain",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 129,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-029F48EC",
    lastOnline: 1736622000,
    realmName: "LivingFlame",
  },
  {
    name: "Zamolxess",
    rankName: "Trial",
    rankIndex: 6,
    level: 60,
    class: "Warrior",
    zone: "Hillsbrad Foothills",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 124,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0281B6D6",
    lastOnline: 1738713600,
    realmName: "LivingFlame",
  },
  {
    name: "Carturesti",
    rankName: "Alt",
    rankIndex: 5,
    level: 1,
    class: "Warrior",
    zone: "Stormwind City",
    note: "Guild Bank Alt",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 150,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B09487",
    lastOnline: 1737666000,
    realmName: "LivingFlame",
  },
  {
    name: "Garthnaxx",
    rankName: "Alt",
    rankIndex: 5,
    level: 1,
    class: "Warrior",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 158,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B59E45",
    lastOnline: 1738908000,
    realmName: "LivingFlame",
  },
  {
    name: "Lightgarth",
    rankName: "Alt",
    rankIndex: 5,
    level: 1,
    class: "Warrior",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 42,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724C3D",
    lastOnline: 1739055600,
    realmName: "LivingFlame",
  },
  {
    name: "Nueraudeloc",
    rankName: "Alt",
    rankIndex: 5,
    level: 1,
    class: "Druid",
    zone: "Darnassus",
    note: "Vasi",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 103,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02757255",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Strangaretu",
    rankName: "Alt",
    rankIndex: 5,
    level: 1,
    class: "Priest",
    zone: "Stormwind City",
    note: "bank",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 24,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01FFF2F0",
    lastOnline: 1738526400,
    realmName: "LivingFlame",
  },
  {
    name: "Jimcarry",
    rankName: "Alt",
    rankIndex: 5,
    level: 6,
    class: "Warrior",
    zone: "Stormwind City",
    note: "Med",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 127,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0287EDBB",
    lastOnline: 1739088000,
    realmName: "LivingFlame",
  },
  {
    name: "Hedir",
    rankName: "Alt",
    rankIndex: 5,
    level: 9,
    class: "Paladin",
    zone: "Dun Morogh",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 153,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B2F830",
    lastOnline: 1736704800,
    realmName: "LivingFlame",
  },
  {
    name: "Garthpump",
    rankName: "Alt",
    rankIndex: 5,
    level: 10,
    class: "Druid",
    zone: "Darnassus",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 140,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A8321C",
    lastOnline: 1737259200,
    realmName: "LivingFlame",
  },
  {
    name: "Loadsofluck",
    rankName: "Alt",
    rankIndex: 5,
    level: 10,
    class: "Hunter",
    zone: "Ironforge",
    note: "Mina lui Seeltze",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 68,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726A39",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Tlbank",
    rankName: "Alt",
    rankIndex: 5,
    level: 10,
    class: "Warrior",
    zone: "Stormwind City",
    note: "(Gbank)",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 76,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0272AABE",
    lastOnline: 1739109600,
    realmName: "LivingFlame",
  },
  {
    name: "Nebunuweed",
    rankName: "Alt",
    rankIndex: 5,
    level: 11,
    class: "Paladin",
    zone: "Dun Morogh",
    note: "alt Oslobanu",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 156,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B54DDC",
    lastOnline: 1737223200,
    realmName: "LivingFlame",
  },
  {
    name: "Statupalma",
    rankName: "Alt",
    rankIndex: 5,
    level: 19,
    class: "Mage",
    zone: "Redridge Mountains",
    note: "Oslobanu alt",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 138,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A53589",
    lastOnline: 1737223200,
    realmName: "LivingFlame",
  },
  {
    name: "Mânuta",
    rankName: "Alt",
    rankIndex: 5,
    level: 22,
    class: "Priest",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 84,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747E41",
    lastOnline: 1733004000,
    realmName: "LivingFlame",
  },
  {
    name: "Okotta",
    rankName: "Alt",
    rankIndex: 5,
    level: 25,
    class: "Mage",
    zone: "Ironforge",
    note: "Vasi",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 75,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027291FA",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Pantelimon",
    rankName: "Alt",
    rankIndex: 5,
    level: 25,
    class: "Paladin",
    zone: "Ironforge",
    note: "Med",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 71,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726C32",
    lastOnline: 1739088000,
    realmName: "LivingFlame",
  },
  {
    name: "Aryaelda",
    rankName: "Alt",
    rankIndex: 5,
    level: 28,
    class: "Paladin",
    zone: "Ironforge",
    note: "Sonia",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 72,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726C8A",
    lastOnline: 1730836800,
    realmName: "LivingFlame",
  },
  {
    name: "Sharkwizard",
    rankName: "Alt",
    rankIndex: 5,
    level: 28,
    class: "Mage",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 36,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0270A93B",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Vosii",
    rankName: "Alt",
    rankIndex: 5,
    level: 30,
    class: "Warrior",
    zone: "Redridge Mountains",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 104,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0275808E",
    lastOnline: 1736704800,
    realmName: "LivingFlame",
  },
  {
    name: "Blackomeh",
    rankName: "Alt",
    rankIndex: 5,
    level: 33,
    class: "Warrior",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 99,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274EF46",
    lastOnline: 1738756800,
    realmName: "LivingFlame",
  },
  {
    name: "Nymerra",
    rankName: "Alt",
    rankIndex: 5,
    level: 38,
    class: "Warlock",
    zone: "Tanaris",
    note: "Sonia",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 70,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726BF6",
    lastOnline: 1738159200,
    realmName: "LivingFlame",
  },
  {
    name: "Karrah",
    rankName: "Alt",
    rankIndex: 5,
    level: 40,
    class: "Priest",
    zone: "Ironforge",
    note: "Sonia",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 47,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725A51",
    lastOnline: 1738764000,
    realmName: "LivingFlame",
  },
  {
    name: "Nemyra",
    rankName: "Alt",
    rankIndex: 5,
    level: 40,
    class: "Hunter",
    zone: "Stormwind City",
    note: "Sonia",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 73,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02727CAF",
    lastOnline: 1738764000,
    realmName: "LivingFlame",
  },
  {
    name: "Alexxacos",
    rankName: "Alt",
    rankIndex: 5,
    level: 42,
    class: "Warlock",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 121,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02800829",
    lastOnline: 1733353200,
    realmName: "LivingFlame",
  },
  {
    name: "Amurg",
    rankName: "Alt",
    rankIndex: 5,
    level: 42,
    class: "Druid",
    zone: "Moonglade",
    note: "Alt Miazazi - Tailor / Alch",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 83,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274202C",
    lastOnline: 1738929600,
    realmName: "LivingFlame",
  },
  {
    name: "Dainai",
    rankName: "Alt",
    rankIndex: 5,
    level: 50,
    class: "Hunter",
    zone: "Stormwind City",
    note: "SlapeR",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 64,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726959",
    lastOnline: 1738702800,
    realmName: "LivingFlame",
  },
  {
    name: "Harapalb",
    rankName: "Alt",
    rankIndex: 5,
    level: 50,
    class: "Priest",
    zone: "Stormwind City",
    note: "Victor",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 39,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724AF6",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Daryele",
    rankName: "Alt",
    rankIndex: 5,
    level: 56,
    class: "Druid",
    zone: "Hillsbrad Foothills",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 102,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02754574",
    lastOnline: 1730746800,
    realmName: "LivingFlame",
  },
  {
    name: "Bibibum",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "Danddy",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 90,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747ED9",
    lastOnline: 1739106000,
    realmName: "LivingFlame",
  },
  {
    name: "Carnagiu",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Rogue",
    zone: "Eastern Plaguelands",
    note: "Dan",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 89,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747ED8",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Ciip",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Warrior",
    zone: "Ironforge",
    note: "Praslea",
    officerNote: "2 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 56,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725C3A",
    lastOnline: 1739055600,
    realmName: "LivingFlame",
  },
  {
    name: "Dand",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 142,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A8A652",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Darkohunt",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "Darko",
    officerNote: "1 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 97,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274ED98",
    lastOnline: 1739066400,
    realmName: "LivingFlame",
  },
  {
    name: "Ddopaladin",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "Delera",
    officerNote: "1.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 132,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A200E4",
    lastOnline: 1739098800,
    realmName: "LivingFlame",
  },
  {
    name: "Devilsoul",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Priest",
    zone: "Stormwind City",
    note: "Dandy",
    officerNote: "1 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 85,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747EB2",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Edir",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Warrior",
    zone: "Stormwind City",
    note: "Duracell",
    officerNote: "0.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 52,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725BAB",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Gretutza",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 17,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01D223AE",
    lastOnline: 1738609200,
    realmName: "LivingFlame",
  },
  {
    name: "Hokahey",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Rogue",
    zone: "Dustwallow Marsh",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 16,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01D13CDB",
    lastOnline: 1739044800,
    realmName: "LivingFlame",
  },
  {
    name: "Justtities",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "Andrei Tank/Dps",
    officerNote: "2 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 65,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0272695E",
    lastOnline: 1734152400,
    realmName: "LivingFlame",
  },
  {
    name: "Kanya",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Rogue",
    zone: "Stranglethorn Vale",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 161,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0273F0F3",
    lastOnline: 1733385600,
    realmName: "LivingFlame",
  },
  {
    name: "Matusica",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Mage",
    zone: "Ironforge",
    note: "Danddy",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 87,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747EBE",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Medlifee",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Mage",
    zone: "Ironforge",
    note: "Alin",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 69,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726BB8",
    lastOnline: 1739088000,
    realmName: "LivingFlame",
  },
  {
    name: "Mmircea",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Paladin",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 157,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B54EE5",
    lastOnline: 1738947600,
    realmName: "LivingFlame",
  },
  {
    name: "Moonblastz",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "Soundvx",
    officerNote: "2 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 35,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02709DDA",
    lastOnline: 1737612000,
    realmName: "LivingFlame",
  },
  {
    name: "Onedouchebag",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Rogue",
    zone: "Ironforge",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 25,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-020C9757",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Ragetrip",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Warrior",
    zone: "Stormwind City",
    note: "Silhouettex",
    officerNote: "0.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 123,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02812E9B",
    lastOnline: 1738638000,
    realmName: "LivingFlame",
  },
  {
    name: "Semaca",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Silithus",
    note: "Alt Ssema",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 41,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724B92",
    lastOnline: 1739030400,
    realmName: "LivingFlame",
  },
  {
    name: "Smallgun",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 88,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747ECD",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Snowiss",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 94,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274911A",
    lastOnline: 1729278000,
    realmName: "LivingFlame",
  },
  {
    name: "Sonía",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Mage",
    zone: "Stormwind City",
    note: "ench/tailor",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 79,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0273E114",
    lastOnline: 1739055600,
    realmName: "LivingFlame",
  },
  {
    name: "Stardragon",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Ironforge",
    note: "alt Palasor",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 62,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0272694E",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Summitshaper",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Ironforge",
    note: "alt Oslobanu",
    officerNote: "0.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 50,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725B94",
    lastOnline: 1739109600,
    realmName: "LivingFlame",
  },
  {
    name: "Tacshhfac",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Druid",
    zone: "Silithus",
    note: "Vasi",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 74,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02729127",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Tragcubile",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "Victor",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 38,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724A79",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Unchiesul",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Warlock",
    zone: "Stormwind City",
    note: "Danddy",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 91,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02747EED",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Zoridezi",
    rankName: "Alt",
    rankIndex: 5,
    level: 60,
    class: "Paladin",
    zone: "Ironforge",
    note: "Alt Miazazi / Alch / Herb",
    officerNote: "1 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 82,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274201B",
    lastOnline: 1739062800,
    realmName: "LivingFlame",
  },
  {
    name: "Deleanu",
    rankName: "Member",
    rankIndex: 4,
    level: 47,
    class: "Hunter",
    zone: "Stranglethorn Vale",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 112,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027896E3",
    lastOnline: 1731578400,
    realmName: "LivingFlame",
  },
  {
    name: "Alexacos",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Rogue",
    zone: "Elwynn Forest",
    note: "Alchemy / Herba",
    officerNote: "2 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 100,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274FB77",
    lastOnline: 1733734800,
    realmName: "LivingFlame",
  },
  {
    name: "Audpriviri",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "FERAL",
    officerNote: "1.5 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 30,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02496094",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Barralion",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Paladin",
    zone: "Gates of Ahn'Qiraj",
    note: "",
    officerNote: "4 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 136,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A2BBFC",
    lastOnline: 1736978400,
    realmName: "LivingFlame",
  },
  {
    name: "Danthegreat",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "Bs/enje",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 101,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02753D9B",
    lastOnline: 1732791600,
    realmName: "LivingFlame",
  },
  {
    name: "Dealyk",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 48,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725B4B",
    lastOnline: 1727121600,
    realmName: "LivingFlame",
  },
  {
    name: "Delera",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "",
    officerNote: "5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 131,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A15E91",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Domion",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Hunter",
    zone: "Tanaris",
    note: "mining/engi",
    officerNote: "1 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 111,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027886C3",
    lastOnline: 1738638000,
    realmName: "LivingFlame",
  },
  {
    name: "Gutgore",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Rogue",
    zone: "Winterspring",
    note: "skin/eng",
    officerNote: "4 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 33,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0265C4CF",
    lastOnline: 1730890800,
    realmName: "LivingFlame",
  },
  {
    name: "Hchief",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "",
    officerNote: "3 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 107,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0275CE69",
    lastOnline: 1739052000,
    realmName: "LivingFlame",
  },
  {
    name: "Jagerbjorn",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "",
    officerNote: "4 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 154,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02B30C77",
    lastOnline: 1738188000,
    realmName: "LivingFlame",
  },
  {
    name: "Mamaomida",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "6 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 28,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0234C3DB",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Meowmeowz",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Priest",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 77,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0272AADE",
    lastOnline: 1727121600,
    realmName: "LivingFlame",
  },
  {
    name: "Mircea",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Hunter",
    zone: "Ironforge",
    note: "",
    officerNote: "5 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 29,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0238BB8E",
    lastOnline: 1738918800,
    realmName: "LivingFlame",
  },
  {
    name: "Needmorage",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Warrior",
    zone: "Ironforge",
    note: "",
    officerNote: "10.5 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 105,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027587DE",
    lastOnline: 1738893600,
    realmName: "LivingFlame",
  },
  {
    name: "Sangedincur",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Warlock",
    zone: "Blasted Lands",
    note: "",
    officerNote: "7 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 144,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A9101C",
    lastOnline: 1739124000,
    realmName: "LivingFlame",
  },
  {
    name: "Silhouettex",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Rogue",
    zone: "Elwynn Forest",
    note: "",
    officerNote: "3 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 108,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0276380B",
    lastOnline: 1736852400,
    realmName: "LivingFlame",
  },
  {
    name: "Soundvx",
    rankName: "Member",
    rankIndex: 4,
    level: 60,
    class: "Priest",
    zone: "Stormwind City",
    note: "All enchants",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 34,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02709DCD",
    lastOnline: 1738234800,
    realmName: "LivingFlame",
  },
  {
    name: "Amocayer",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "19 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 20,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01DA3BF8",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Chopinwow",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Warrior",
    zone: "Stormwind City",
    note: "",
    officerNote: "",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 93,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027490F8",
    lastOnline: 1729328400,
    realmName: "LivingFlame",
  },
  {
    name: "Darkoomeh",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "",
    officerNote: "22 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 98,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0274EEE0",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Dohko",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Mage",
    zone: "Stormwind City",
    note: "Deceneu",
    officerNote: "10.5 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 134,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A28FD2",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Dorpf",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Hunter",
    zone: "Searing Gorge",
    note: "Kanya",
    officerNote: "4 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 115,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027D881E",
    lastOnline: 1734976800,
    realmName: "LivingFlame",
  },
  {
    name: "Hopsieu",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Druid",
    zone: "Stormwind City",
    note: "",
    officerNote: "24 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 22,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01F40E27",
    lastOnline: 1739052000,
    realmName: "LivingFlame",
  },
  {
    name: "Illusionx",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Paladin",
    zone: "Felwood",
    note: "",
    officerNote: "12 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 21,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01E15565",
    lastOnline: 1739055600,
    realmName: "LivingFlame",
  },
  {
    name: "Junkt",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Warrior",
    zone: "Stormwind City",
    note: "",
    officerNote: "7 (prezente raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 135,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02A28FE9",
    lastOnline: 1737313200,
    realmName: "LivingFlame",
  },
  {
    name: "Kany",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Warrior",
    zone: "Zul'Gurub",
    note: "",
    officerNote: "22.5 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 19,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-01D7A62B",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Lásthit",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Hunter",
    zone: "Stormwind City",
    note: "lw/eng",
    officerNote: "6 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 66,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027269BE",
    lastOnline: 1732647600,
    realmName: "LivingFlame",
  },
  {
    name: "Medl",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Priest",
    zone: "Stormwind City",
    note: "ench/tailor main",
    officerNote: "22.5 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 61,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726941",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Miazazi",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Priest",
    zone: "Wetlands",
    note: "Tailoring / Enchanting",
    officerNote: "28 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 92,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02748FA7",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Nelful",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "Miner/Inginer",
    officerNote: "11 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 95,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02749345",
    lastOnline: 1736719200,
    realmName: "LivingFlame",
  },
  {
    name: "Nesimtitul",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Hunter",
    zone: "Duskwood",
    note: "Mugur",
    officerNote: "23 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 27,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-021A5984",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Oslobanu",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Warrior",
    zone: "Ironforge",
    note: "bs",
    officerNote: "27.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARRIOR",
    achievementPoints: -1,
    achievementRank: 53,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725BC1",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Praslea",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Hunter",
    zone: "Ironforge",
    note: "eng",
    officerNote: "27 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "HUNTER",
    achievementPoints: -1,
    achievementRank: 67,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-027269E0",
    lastOnline: 1739055600,
    realmName: "LivingFlame",
  },
  {
    name: "Rtep",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Mage",
    zone: "Stormwind City",
    note: "",
    officerNote: "23 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "MAGE",
    achievementPoints: -1,
    achievementRank: 51,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725B97",
    lastOnline: 1739116800,
    realmName: "LivingFlame",
  },
  {
    name: "Ruub",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Rogue",
    zone: "Blackrock Mountain",
    note: "",
    officerNote: "4 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 113,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0278B005",
    lastOnline: 1737925200,
    realmName: "LivingFlame",
  },
  {
    name: "Shnneb",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Paladin",
    zone: "Stormwind City",
    note: "eng/bs",
    officerNote: "24.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 57,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725CC7",
    lastOnline: 1739113200,
    realmName: "LivingFlame",
  },
  {
    name: "Sseema",
    rankName: "Raider",
    rankIndex: 3,
    level: 60,
    class: "Warlock",
    zone: "Stormwind City",
    note: "alch/tailor",
    officerNote: "28.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "WARLOCK",
    achievementPoints: -1,
    achievementRank: 54,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725C22",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Feyré",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Druid",
    zone: "Ironforge",
    note: "Sonia",
    officerNote: "28.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "DRUID",
    achievementPoints: -1,
    achievementRank: 80,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0273E13C",
    lastOnline: 1739052000,
    realmName: "LivingFlame",
  },
  {
    name: "Filamina",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Priest",
    zone: "Stormwind City",
    note: "alch/herb",
    officerNote: "25 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PRIEST",
    achievementPoints: -1,
    achievementRank: 63,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02726956",
    lastOnline: 1739055600,
    realmName: "LivingFlame",
  },
  {
    name: "Liquidslaper",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Paladin",
    zone: "Winterspring",
    note: "Mining/Herb",
    officerNote: "4 (Prezente Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 43,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02724C7F",
    lastOnline: 1738872000,
    realmName: "LivingFlame",
  },
  {
    name: "Palasor",
    rankName: "Officer",
    rankIndex: 2,
    level: 60,
    class: "Paladin",
    zone: "Ironforge",
    note: "bs/min",
    officerNote: "27.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "PALADIN",
    achievementPoints: -1,
    achievementRank: 58,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-02725D19",
    lastOnline: 1739127600,
    realmName: "LivingFlame",
  },
  {
    name: "Slaperr",
    rankName: "Guild Master",
    rankIndex: 1,
    level: 60,
    class: "Rogue",
    zone: "Stormwind City",
    note: "lw/skinati dragonii",
    officerNote: "25.5 (Prezenta Raid)",
    isOnline: false,
    status: 0,
    classFileName: "ROGUE",
    achievementPoints: -1,
    achievementRank: 59,
    isMobile: false,
    isSoREligible: false,
    repStandingID: 3,
    GUID: "Player-5827-0272691F",
    lastOnline: 1739052000,
    realmName: "LivingFlame",
  },
];
